import json

FC = json.dumps({"pdf":"#ff4d4f","epub":"#1677ff","mobi":"#52c41a","txt":"#666","md":"#722ed1"})
CC = json.dumps({"计算机与编程":"#1677ff","历史与人文":"#fa8c16","文学与小说":"#52c41a","哲学与思想":"#722ed1","科学与科普":"#13c2c2","经济与管理":"#eb2f96","心理与成长":"#fa541c","教育学习":"#2f54eb","艺术设计":"#a0d911","社会与政治":"#f5222d","生活与健康":"#7cb305","其他":"#999"}, ensure_ascii=False)

css = "*{margin:0;padding:0;box-sizing:border-box}body{font-family:sans-serif;background:#f5f5f5;display:flex;min-height:100vh}nav{width:180px;background:#fff;padding:20px 0;border-right:1px solid #eee}nav h2{padding:0 20px 16px;color:#1677ff;font-size:18px}nav a{display:block;padding:10px 20px;color:#333;text-decoration:none;font-size:14px;cursor:pointer}nav a:hover{background:#e6f4ff;color:#1677ff}main{flex:1;padding:20px;overflow-y:auto}.t{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;margin:2px;color:#fff}.btn{padding:6px 14px;border:1px solid #ddd;border-radius:4px;cursor:pointer;background:#fff;margin:2px}.bb{background:#1677ff;color:#fff;border-color:#1677ff}input,select{padding:6px 10px;border:1px solid #ddd;border-radius:4px}.bx{background:#fff;padding:20px;border-radius:8px;text-align:center;min-width:130px}.bx .n{font-size:32px;font-weight:bold}.bx .l{font-size:13px;color:#999}.pn{background:#fff;padding:16px;border-radius:8px}.bi{background:#fff;border-radius:8px;padding:14px;margin-bottom:8px;display:flex;gap:12px;align-items:center;cursor:pointer;box-shadow:0 1px 3px rgba(0,0,0,.08)}.cv{width:60px;height:80px;object-fit:cover;border-radius:4px;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;font-size:28px;display:flex;align-items:center;justify-content:center;flex-shrink:0}.cv-lg{width:200px;height:260px;object-fit:contain;border-radius:8px;background:#f5f5f5}.cv-fb{width:200px;height:260px;border-radius:8px;background:linear-gradient(135deg,#667eea,#764ba2);display:flex;align-items:center;justify-content:center;color:#fff;font-size:64px;flex-shrink:0}.mbg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.5);z-index:999;display:flex;align-items:center;justify-content:center;padding:20px}.mn{background:#fff;border-radius:12px;padding:24px;max-width:800px;width:100%;max-height:90vh;overflow-y:auto}"

js = r"""var FC=__FC__;var CC=__CC__;var bP=1,bF='',bS='';
function M(h){document.getElementById('m').innerHTML=h}
function Q(s){return (s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function G(u,cb){var x=new XMLHttpRequest();x.open('GET','/api'+u);x.onload=function(){if(x.status==200)cb(JSON.parse(x.responseText));else cb(null)};x.onerror=function(){cb(null)};x.send()}
function P(u,d,cb){var x=new XMLHttpRequest();x.open('POST','/api'+u);x.setRequestHeader('Content-Type','application/json');x.onload=function(){if(x.status==200)cb(JSON.parse(x.responseText));else cb(null)};x.onerror=function(){cb(null)};x.send(JSON.stringify(d||{}))}
function L(i){if(i==0)H();else if(i==1){bP=1;B()}else if(i==2)ME()}
function H(){M('<h2>Loading...</h2>');G('/stats',function(s){if(!s)return;var h='<h2>首页</h2><div style=display:flex;gap:12px;flex-wrap:wrap;margin-bottom:16px>';h+='<div class=bx><div class=n style=color:#1677ff>'+(s.total_books||0)+'</div><div class=l>书籍</div></div>';h+='<div class=bx><div class=n style=color:#52c41a>'+(s.with_summary||0)+'</div><div class=l>已摘要</div></div>';h+='<div class=bx><div class=n style=color:#fa8c16>'+Object.keys(s.by_category||{}).length+'</div><div class=l>分类</div></div></div>';var f='',c='';for(var k in s.by_format)f+='<span class=t style=background:'+(FC[k]||'#999')+'>'+k.toUpperCase()+' '+s.by_format[k]+'本</span> ';for(var k in s.by_category)c+='<span class=t style=background:'+(CC[k]||'#999')+'>'+k+' '+s.by_category[k]+'本</span> ';h+='<div style=display:flex;gap:16px;flex-wrap:wrap><div class=pn style=flex:1;min-width:300px><h3>格式分布</h3>'+f+'</div><div class=pn style=flex:1;min-width:300px><h3>分类分布</h3>'+c+'</div></div>';h+='<div class=pn style=margin-top:16px><h3>导入新书</h3>';h+='<button class=btn bb onclick=document.getElementById(\"f1\").click() style=margin-right:8px>选择文件</button>';h+='<button class=btn bb onclick=document.getElementById(\"f2\").click() style=margin-right:8px>选择文件夹</button>';h+='<button class=btn onclick=IMP()>扫描 F:\\书籍</button>';h+='<div id=ir style=margin-top:8px;font-size:13px></div></div>';M(h);document.getElementById('f1').onchange=function(){UP(this.files)};document.getElementById('f2').onchange=function(){UP(this.files)}})}
var _f=[],_i=0,_ok=0,_d=0,_e=0;
function UP(fs){_f=Array.from(fs);_i=0;_ok=0;_d=0;_e=0;NX()}
function NX(){if(_i>=_f.length){document.getElementById('ir').innerHTML='完成! 新'+_ok+' 重'+_d;return}var fd=new FormData();fd.append('file',_f[_i]);_i++;var x=new XMLHttpRequest();x.open('POST','/api/books/upload');x.onload=function(){try{var r=JSON.parse(x.responseText);if(r.type=='archive'){_ok+=r.success||0;_d+=r.duplicates||0}else if(r.type=='duplicate')_d++;else if(r.type=='book')_ok++;else _e++}catch(e){_e++}document.getElementById('ir').innerHTML=_i+'/'+_f.length+' 新'+_ok+' 重'+_d;NX()};x.onerror=function(){_e++;NX()};x.send(fd)}
function IMP(){document.getElementById('ir').innerHTML='扫描中...';P('/import-scan',{dir:'F:\\书籍'},function(r){if(!r||r.error)document.getElementById('ir').innerHTML='失败';else document.getElementById('ir').innerHTML='新增 '+r.new+' 跳过 '+r.dupes+' <a href=# onclick=location.reload() style=color:#1677ff>刷新</a>'})}
function B(){M('<h2>Loading...</h2>');var u='/books?page='+bP+'&page_size=20'+(bF?'&format='+bF:'');if(bS)u='/search?q='+encodeURIComponent(bS)+'&page='+bP+'&page_size=20'+(bF?'&format='+bF:'');G(u,function(d){if(!d)return;var h='<h2>书库</h2><div style=display:flex;gap:8px;margin-bottom:12px;flex-wrap:wrap><input id=bs placeholder=搜索 style=flex:1;min-width:180px;padding:6px 10px;border:1px solid #ddd;border-radius:4px><select id=bf><option value=>全部</option><option value=pdf>PDF</option><option value=epub>EPUB</option></select><button class=btn bb onclick=SR()>搜索</button></div><div style=color:#999;margin-bottom:8px>共 '+d.total+' 本</div>';for(var i=0;i<d.items.length;i++){var b=d.items[i],ct='';for(var j=0;j<(b.categories||[]).length;j++)ct+='<span class=t style=background:'+(CC[b.categories[j].name]||'#999')+'>'+b.categories[j].name+'</span> ';var cv=b.cover_path?'<img src=/api/covers/'+b.id+'.jpg class=cv>':'<div class=cv>📚</div>';h+='<div class=bi onclick=D(\''+b.id+'\')>'+cv+'<div style=flex:1;min-width:0><div style=font-weight:bold>'+Q(b.title)+'</div><div style=font-size:12px;color:#999>'+Q((b.authors||[]).map(function(a){return a.name}).join(', '))+'</div><div style=margin-top:4px>'+ct+'<span class=t style=background:'+(FC[b.file_format]||'#999')+'>'+b.file_format.toUpperCase()+'</span></div></div></div>'}if(d.total>20){h+='<div style=text-align:center;margin-top:12px>';for(var i=1;i<=Math.min(Math.ceil(d.total/20),20);i++)h+='<button class=btn'+(i===bP?' bb':'')+' onclick=bP='+i+';B()>'+i+'</button> ';h+='</div>'}M(h)})}
function SR(){bS=document.getElementById('bs').value;bF=document.getElementById('bf').value;bP=1;B()}
function D(id){G('/books/'+id,function(b){if(!b)return;var ct='';for(var j=0;j<(b.categories||[]).length;j++)ct+='<span class=t style=background:'+(CC[b.categories[j].name]||'#999')+'>'+b.categories[j].name+'</span> ';var cv=b.cover_path?'<img src=/api/covers/'+b.id+'.jpg class=cv-lg>':'<div class=cv-fb>📚</div>';var h='<div class=mbg onclick=if(event.target===this)this.remove()><div class=mn onclick=event.stopPropagation()><h2>'+Q(b.title)+'</h2><div style=display:flex;gap:24px;flex-wrap:wrap><div>'+cv+'</div><div style=flex:1;min-width:240px><p>作者: '+Q((b.authors||[]).map(function(a){return a.name}).join(', '))+'</p><p>格式: '+b.file_format.toUpperCase()+' | '+(b.file_size/1024/1024).toFixed(2)+'MB | 页数: '+(b.page_count||'-')+'</p><div style=margin:8px 0>'+ct+'</div>';if(b.summary)h+='<div style=background:#f9f9f9;padding:12px;border-radius:8px;margin:12px 0><b>AI 摘要</b><p style=white-space:pre-wrap;margin-top:8px;font-size:13px>'+Q(b.summary)+'</p></div>';var ru='/api/books/'+b.id+'/'+(b.file_format=='pdf'?'file':'read');h+='</div></div><div style=margin-top:16px><button class=btn bb onclick=event.stopPropagation();window.open(\''+ru+'\',\'_blank\')>阅读</button> <button class=btn onclick=this.closest(\'.mbg\').remove()>关闭</button></div></div></div>';document.body.insertAdjacentHTML('beforeend',h)})}
function ME(){M('<h2>Loading...</h2>');G('/media?page=1&page_size=100',function(d){if(!d)return;var h='<h2>媒体库</h2><div style=color:#999;margin-bottom:8px>共 '+d.total+' 个</div>';for(var i=0;i<d.items.length;i++){var m=d.items[i];var bg=m.media_type=='audio'?'#667eea,#764ba2':'#f093fb,#f5576c';var icon=m.media_type=='audio'?'🎵':'🎬';var dur=m.duration?Math.floor(m.duration/60)+':'+String(Math.floor(m.duration%60)).padStart(2,'0'):'--';h+='<div class=bi onclick=PM(\''+m.id+'\')><div style=width:60px;height:60px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:28px;background:linear-gradient(135deg,'+bg+');color:#fff>'+icon+'</div><div style=flex:1><div style=font-weight:bold>'+Q(m.title)+'</div><div style=font-size:12px;color:#999>'+Q(m.artist)+' | '+m.file_format.toUpperCase()+' | '+dur+'</div></div></div>'}M(h)})}
function PM(id){G('/media/'+id,function(m){if(!m)return;var p=m.media_type=='audio'?'<audio src=/api/media/'+id+'/file controls style=width:100%;margin-top:12px></audio>':'<video src=/api/media/'+id+'/file controls style=width:100%;max-height:60vh;margin-top:12px></video>';var h='<div class=mbg onclick=if(event.target===this)this.remove()><div class=mn onclick=event.stopPropagation()><h2>'+Q(m.title)+'</h2><p>'+Q(m.artist)+' | '+m.file_format.toUpperCase()+'</p>'+p+'<button class=btn style=margin-top:12px onclick=this.closest(\'.mbg\').remove()>关闭</button></div></div>';document.body.insertAdjacentHTML('beforeend',h)})}
L(0)"""

js = js.replace("__FC__", FC).replace("__CC__", CC)

html = '<!DOCTYPE html><html lang=zh><head><meta charset=UTF-8><title>我的图书馆</title><style>' + css + '</style></head><body><nav><h2>📚 我的图书馆</h2><a onclick=L(0)>🏠 首页</a><a onclick=L(1)>📖 书库</a><a onclick=L(2)>🎧 媒体库</a></nav><main id=m></main><input type=file id=f1 hidden multiple accept=.pdf,.epub,.mobi,.azw3,.txt,.md,.zip,.rar,.7z><input type=file id=f2 hidden webkitdirectory><script>' + js + '</script></body></html>'

open("app.html","w",encoding="utf-8").write(html)
print("OK - " + str(len(html)) + " bytes")

